LANGUAGES = {
    'en': {
        'here': 'here',
        'title': 'Prompt Enhancer',
        'subtitle': 'Prompt Engineering Techniques at Your Fingertips!',
        'api_key_title': 'Enter your OpenAI API key',
        'api_key_placeholder': 'Enter your OpenAI API key',
        'api_key_info': 'You can get your OpenAI API key',
        'api_key_error': 'Please enter your OpenAI API key to continue.',
        'skills_title': 'Prompt Engineering Skills',
        'skills_info': 'This section is based on the paper',
        'skills_warning': 'Please note that the effectiveness of these skills may vary depending on the specific use case and the model being used.',
        'select_all': 'Select All',
        'prompt_structure': 'Prompt Structure',
        'specificity': 'Specificity',
        'content_style': 'Content Style',
        'complex_tasks': 'Complex Tasks',
        'enhance_title': 'Enhance Your Prompt',
        'original_prompt': 'Original Prompt',
        'prompt_placeholder': 'Enter your prompt here...',
        'magical_phrases': 'Magical Phrases',
        'select_model': 'Select Model',
        'english_option': 'Keep the enhanced prompt in English',
        'simplified_option': 'Apply all selected skills at once',
        'enhance_button': 'Enhance!',
        'enter_prompt': 'Please enter your prompt.',
        'processing': 'Processing...',
        'enhancement_success': 'Enhancement completed!',
        'enhanced_prompt': 'Enhanced Prompt',
        'contact_email': 'Contact: lim.gadi@gmail.com',
        'contact_github': 'GitHub: [@lim-hyo-jeong](https://github.com/lim-hyo-jeong)',
        'learn_more': 'Learn more about this section',
        'audience_integration': 'Audience Integration',
        'audience_integration_desc': 'Integrate the intended audience in the prompt.',
        'affirmative_sentencing': 'Affirmative Sentencing',
        'affirmative_sentencing_desc': 'Employ affirmative directives such as \'do,\' while steering clear of negative language like \'don\'t\'.',
        'output_primers': 'Output Primers',
        'output_primers_desc': 'Use output primers, which involve concluding the prompt with the beginning of the desired output.',
        'delimiters': 'Delimiters',
        'delimiters_desc': 'Use delimiters to distinguish specific segments of text within the prompt.',
        'formatted_prompt': 'Formatted Prompt',
        'formatted_prompt_desc': 'Use Formatted prompt to allow the model to understand the requirements structurally.',
        'fewshot_prompting': 'Few-Shot Prompting',
        'fewshot_prompting_desc': 'Implement example-driven prompting.',
        'guideline_indicators': 'Guideline Indicators',
        'guideline_indicators_desc': 'Clarify the requirements using keywords, regulations, hints, or instructions.',
        'no_politeness': 'No Politeness',
        'no_politeness_desc': 'If you prefer more concise answers, remove any unnecessary polite or indirect phrases in the prompt.',
        'imperative_task': 'Imperative Task',
        'imperative_task_desc': 'Incorporate the following phrases: "Your task is" and "You MUST".',
        'penalty_warning': 'Penalty Warning',
        'penalty_warning_desc': 'Incorporate the following phrases: "You will be penalized".',
        'role_assignment': 'Role Assignment',
        'role_assignment_desc': 'Assign a specific role or persona to the model within the prompt.',
        'echo_directive': 'Echo Directive',
        'echo_directive_desc': 'Repeat a specific word or phrase multiple times within a prompt.',
        'task_decomposition': 'Task Decomposition',
        'task_decomposition_desc': 'Break down complex tasks into a sequence of simpler prompts in an interactive conversation.',
        'step_by_step': 'Take a deep breath and work on this step by step.',
        'tipping': 'I\'m going to tip $200 for a better solution!',
        'important_to_career': 'This is very important to my career.',
        'explain_beginner': 'Explain to me as if I\'m a beginner.',
        'detailed_writing': 'Write a detailed text for me by adding all the information necessary.',
        'human_like_response': 'Answer in a natural, human-like manner.',
        'unbiased_response': 'Ensure that your answer is unbiased and avoids relying on stereotypes.',
        'enhancement_skill': 'Your prompt has been enhanced with "{skill}"!',
        'enhancement_phrase': 'Your prompt has been enhanced with "{phrase}"!',
        'audience_integration_title': 'Audience Integration',
        'affirmative_sentencing_title': 'Affirmative Sentencing',
        'output_primers_title': 'Output Primers',
        'delimiters_title': 'Delimiters',
        'formatted_prompt_title': 'Formatted Prompt',
        'fewshot_prompting_title': 'Few-Shot Prompting',
        'guideline_indicators_title': 'Guideline Indicators',
        'no_politeness_title': 'No Politeness',
        'imperative_task_title': 'Imperative Task',
        'penalty_warning_title': 'Penalty Warning',
        'role_assignment_title': 'Role Assignment',
        'echo_directive_title': 'Echo Directive',
        'task_decomposition_title': 'Task Decomposition'
    },
    'vi': {
        'here': 'ở đây',
        'title': 'Prompt Enhancer',
        'subtitle': 'Kỹ Thuật Prompt Engineering Ngay Trong Tầm Tay!',
        'api_key_title': 'Nhập API Key OpenAI',
        'api_key_placeholder': 'Nhập API Key OpenAI của bạn',
        'api_key_info': 'Bạn có thể lấy API Key OpenAI',
        'api_key_error': 'Vui lòng nhập API Key OpenAI để tiếp tục.',
        'skills_title': 'Kỹ Thuật Prompt Engineering',
        'skills_info': 'Phần này dựa trên nghiên cứu từ bài báo',
        'skills_warning': 'Lưu ý: Hiệu quả của các kỹ thuật này có thể khác nhau tùy thuộc vào từng trường hợp cụ thể và mô hình được sử dụng.',
        'select_all': 'Chọn Tất Cả',
        'prompt_structure': 'Cấu Trúc Prompt',
        'specificity': 'Tính Cụ Thể',
        'content_style': 'Phong Cách Nội Dung',
        'complex_tasks': 'Tác Vụ Phức Tạp',
        'enhance_title': 'Nâng Cấp Prompt',
        'original_prompt': 'Prompt Gốc',
        'prompt_placeholder': 'Nhập prompt của bạn vào đây...',
        'magical_phrases': 'Cụm Từ Kỳ Diệu',
        'select_model': 'Chọn Mô Hình',
        'english_option': 'Giữ prompt đã nâng cấp bằng tiếng Anh',
        'simplified_option': 'Áp dụng tất cả kỹ thuật đã chọn cùng lúc',
        'enhance_button': 'Nâng Cấp!',
        'enter_prompt': 'Vui lòng nhập prompt của bạn.',
        'processing': 'Đang xử lý...',
        'enhancement_success': 'Nâng cấp hoàn tất!',
        'enhanced_prompt': 'Prompt Đã Nâng Cấp',
        'contact_email': 'Liên hệ: lim.gadi@gmail.com',
        'contact_github': 'GitHub: [@lim-hyo-jeong](https://github.com/lim-hyo-jeong)',
        'learn_more': 'Tìm hiểu thêm về phần này',
        'audience_integration': 'Tích Hợp Đối Tượng',
        'audience_integration_desc': 'Tích hợp đối tượng mục tiêu vào prompt.',
        'affirmative_sentencing': 'Câu Khẳng Định',
        'affirmative_sentencing_desc': 'Sử dụng các chỉ thị khẳng định như \'hãy làm\', tránh ngôn ngữ phủ định như \'đừng\'.',
        'output_primers': 'Mẫu Đầu Ra',
        'output_primers_desc': 'Sử dụng mẫu đầu ra, bao gồm việc kết thúc prompt bằng phần đầu của kết quả mong muốn.',
        'delimiters': 'Dấu Phân Cách',
        'delimiters_desc': 'Sử dụng dấu phân cách để phân biệt các phần cụ thể trong prompt.',
        'formatted_prompt': 'Prompt Có Cấu Trúc',
        'formatted_prompt_desc': 'Sử dụng prompt có cấu trúc để giúp mô hình hiểu rõ yêu cầu.',
        'fewshot_prompting': 'Prompt Có Ví Dụ',
        'fewshot_prompting_desc': 'Áp dụng kỹ thuật prompt với ví dụ minh họa.',
        'guideline_indicators': 'Chỉ Dẫn Rõ Ràng',
        'guideline_indicators_desc': 'Làm rõ yêu cầu bằng từ khóa, quy định, gợi ý hoặc hướng dẫn.',
        'no_politeness': 'Không Lịch Sự',
        'no_politeness_desc': 'Nếu bạn muốn câu trả lời ngắn gọn, hãy loại bỏ các cụm từ lịch sự hoặc gián tiếp không cần thiết.',
        'imperative_task': 'Nhiệm Vụ Bắt Buộc',
        'imperative_task_desc': 'Thêm các cụm từ: "Nhiệm vụ của bạn là" và "Bạn PHẢI".',
        'penalty_warning': 'Cảnh Báo Phạt',
        'penalty_warning_desc': 'Thêm cụm từ: "Bạn sẽ bị phạt".',
        'role_assignment': 'Gán Vai Trò',
        'role_assignment_desc': 'Gán một vai trò hoặc nhân cách cụ thể cho mô hình trong prompt.',
        'echo_directive': 'Lặp Lại Chỉ Thị',
        'echo_directive_desc': 'Lặp lại một từ hoặc cụm từ cụ thể nhiều lần trong prompt.',
        'task_decomposition': 'Phân Tách Nhiệm Vụ',
        'task_decomposition_desc': 'Chia nhỏ các nhiệm vụ phức tạp thành chuỗi các prompt đơn giản hơn.',
        'step_by_step': 'Hãy hít thở sâu và giải quyết vấn đề này từng bước một.',
        'tipping': 'Tôi sẽ thưởng $200 cho giải pháp tốt hơn!',
        'important_to_career': 'Điều này rất quan trọng đối với sự nghiệp của tôi.',
        'explain_beginner': 'Giải thích cho tôi như thể tôi là người mới bắt đầu.',
        'detailed_writing': 'Viết một văn bản chi tiết bằng cách thêm tất cả thông tin cần thiết.',
        'human_like_response': 'Trả lời một cách tự nhiên, giống như con người.',
        'unbiased_response': 'Đảm bảo câu trả lời của bạn không thiên vị và tránh dựa vào định kiến.',
        'enhancement_skill': 'Prompt của bạn đã được nâng cấp với "{skill}"!',
        'enhancement_phrase': 'Prompt của bạn đã được nâng cấp với "{phrase}"!',
        'audience_integration_title': 'Tích Hợp Đối Tượng (Audience Integration)',
        'affirmative_sentencing_title': 'Câu Khẳng Định (Affirmative Sentencing)',
        'output_primers_title': 'Mẫu Đầu Ra (Output Primers)',
        'delimiters_title': 'Dấu Phân Cách (Delimiters)',
        'formatted_prompt_title': 'Prompt Có Cấu Trúc (Formatted Prompt)',
        'fewshot_prompting_title': 'Prompt Có Ví Dụ (Few-Shot Prompting)',
        'guideline_indicators_title': 'Chỉ Dẫn Rõ Ràng (Guideline Indicators)',
        'no_politeness_title': 'Không Lịch Sự (No Politeness)',
        'imperative_task_title': 'Nhiệm Vụ Bắt Buộc (Imperative Task)',
        'penalty_warning_title': 'Cảnh Báo Phạt (Penalty Warning)',
        'role_assignment_title': 'Gán Vai Trò (Role Assignment)',
        'echo_directive_title': 'Lặp Lại Chỉ Thị (Echo Directive)',
        'task_decomposition_title': 'Phân Tách Nhiệm Vụ (Task Decomposition)'
    }
} 